name: Pipeline MLOps - DVC y Fases

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  prepare-environment:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11 y caché de pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: '**/requirements2-mlops.txt'

      - name: Crear .venv e instalar dependencias (rápido)
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements2-mlops.txt

      - name: Añadir .venv/bin al PATH
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

  dvc-check:
    needs: prepare-environment
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    env:
      GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
      GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
      G_DRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.G_DRIVE_SERVICE_ACCOUNT_JSON }}
      TOKEN_GDRIVE_JSON: ${{ secrets.TOKEN_GDRIVE_JSON }}
      TOKEN_GDRIVE_DVC_JSON: ${{ secrets.TOKEN_GDRIVE_DVC_JSON }}
      FASE0_FOLDER_ID: ${{ vars.FASE0_FOLDER_ID }}
      FASE1_FOLDER_ID: ${{ vars.FASE1_FOLDER_ID }}
      FASE2_FOLDER_ID: ${{ vars.FASE2_FOLDER_ID }}
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11 y caché de pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: '**/requirements2-mlops.txt'

      - name: Crear .venv e instalar dependencias (rápido)
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements2-mlops.txt

      - name: Añadir .venv/bin al PATH
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Validar secrets requeridos
        run: |
          test -n "$GDRIVE_CLIENT_ID" || (echo "Falta secret GDRIVE_CLIENT_ID" && exit 1)
          test -n "$GDRIVE_CLIENT_SECRET" || (echo "Falta secret GDRIVE_CLIENT_SECRET" && exit 1)
          test -n "$FASE0_FOLDER_ID" || (echo "Falta variable FASE0_FOLDER_ID" && exit 1)
          test -n "$TOKEN_GDRIVE_DVC_JSON" || (echo "Falta secret TOKEN_GDRIVE_DVC_JSON" && exit 1)

      - name: Crear token.json de GDrive
        run: |
          printf '%s' "$TOKEN_GDRIVE_DVC_JSON" > .mlops_tools/credentials/dvc_token.json
          test -s .mlops_tools/credentials/dvc_token.json || (echo "token_dvc.json vacio" && exit 1)
          
          printf '%s' "$TOKEN_GDRIVE_JSON" > .mlops_tools/credentials/gdrive_token.json
          test -s .mlops_tools/credentials/gdrive_token.json || (echo "token_gdrive.json vacio" && exit 1)
          
          printf '%s' "$G_DRIVE_SERVICE_ACCOUNT_JSON" > .mlops_tools/credentials/service_account.json
          test -s .mlops_tools/credentials/service_account.json || (echo "service_account.json vacio" && exit 1)

      - name: Configurar DVC remote (GDrive)
        working-directory: .mlops_tools
        run: make dvc_setup_fase0

      - name: Descargar datos de DVC
        working-directory: .mlops_tools
        run: make dvc_pull_fase0 

      - name: Verificar que los datos se descargaron
        run: |
          ls -la data
          wc data/raw.csv

      - name: Subir raw.csv como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: raw-data
          path: data/raw.csv
          retention-days: 1

  fase1:
    needs: dvc-check
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11 y caché de pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: '**/requirements2-mlops.txt'

      - name: Crear .venv e instalar dependencias (rápido)
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements2-mlops.txt

      - name: Añadir .venv/bin al PATH
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Descargar Artifact de datos raw
        uses: actions/download-artifact@v4
        with:
          name: raw-data
          path: data/raw.csv

      - name: Crear variante Fase 1
        run: make variant1 VARIANT=v001 RAW=./data/raw.csv CLEANING_STRATEGY=basic NAN_VALUES="[-999999]"
      
      - name: Subir resultados de la variante
        uses: actions/upload-artifact@v4
        with:
          name: variant-f1v001-variants
          path: executions/01_explore/v001/variants.yaml 
          retention-days: 1
      
      - name: Ejecutar script de Fase 1
        run: make script1-run VARIANT=v001


      - name: Subir ejecución de Fase 1
        uses: actions/upload-artifact@v4
        with:
          name: run-f1v001-results
          path: executions/01_explore/v001/
          retention-days: 1

      - name: Verificar resultados de Fase 1
        working-directory: executions/01_explore/v001/
        run: make script1-check-results VARIANT=v001


  fase2:
    needs: fase1
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11 y caché de pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: '**/requirements2-mlops.txt'

      - name: Crear .venv e instalar dependencias (rápido)
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements2-mlops.txt

      - name: Añadir .venv/bin al PATH
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Descargar Artifact de fase 1 variants
        uses: actions/download-artifact@v4
        with:
          name: variant-f1v001-variants 
          path: executions/01_explore/variants.yaml

      - name: Descargar Artifact de fase 1
        uses: actions/download-artifact@v4
        with:
          name: run-f1v001-results
          path: executions/01_explore/v001/

      - name: Crear variante Fase 2
        run: make variant2 VARIANT=v011 PARENT=v001 BANDS="10 25 50 75 90" STRATEGY=both NAN=keep

      - name: Subir resultados de la variante
        uses: actions/upload-artifact@v4
        with:
          name: variant-f2v011-variants
          path: executions/02_prepareeventsds/variants.yaml 
          retention-days: 1
      - name: Ejecutar script de Fase 2
        run: make script2-run VARIANT=v011

      - name: Subir ejecución de Fase 2
        uses: actions/upload-artifact@v4
        with:
          name: run-f2v011-results
          path: executions/02_prepareeventsds/v011/
          retention-days: 1

      - name: Verificar resultados de Fase 2
        run: make script2-check-results VARIANT=v011
# make variant2 VARIANT=v011 PARENT=v001 BANDS="10 25 50 75 90" STRATEGY=both NAN=keep
# make script2-run VARIANT=v011
# make script2-check-results VARIANT=v011

  fase3:
    needs: fase2
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11 y caché de pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: '**/requirements2-mlops.txt'

      - name: Crear .venv e instalar dependencias (rápido)
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements2-mlops.txt

      - name: Añadir .venv/bin al PATH
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Descargar Artifact de fase 2 variants
        uses: actions/download-artifact@v4
        with:
          name: variant-f2v011-variants
          path: executions/02_prepareeventsds/variants.yaml

      - name: Descargar Artifact de fase 2
        uses: actions/download-artifact@v4
        with:
          name: run-f2v011-results
          path: executions/02_prepareeventsds/v011/
      
      - name: Crear variante Fase 3
        run: make variant3 VARIANT=v111 PARENT=v011 OW=600 LT=300 PW=600 WS=synchro NAN=preserve
        
      - name: Subir resultados de la variante
        uses: actions/upload-artifact@v4
        with:
          name: variant-f3v111-variants
          path: executions/03_preparewindowsds/variants.yaml
          retention-days: 1

      - name: Ejecutar script de Fase 3
        run: make script3-run VARIANT=v111

      - name: Subir ejecución de Fase 3
        uses: actions/upload-artifact@v4
        with:
          name: run-f3v111-results
          path: executions/03_preparewindowsds/v111/
          retention-days: 1
        
      - name: Verificar resultados de Fase 3
        run: make script3-check-results VARIANT=v111
        
# make variant3 VARIANT=v111 PARENT=v011 OW=600 LT=300 PW=600 WS=synchro NAN=preserve
# make script3-run VARIANT=v111
# make script3-check-results VARIANT=v111
  fase4:
    needs: fase3
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11 y caché de pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: '**/requirements2-mlops.txt'

      - name: Crear .venv e instalar dependencias (rápido)
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements2-mlops.txt

      - name: Añadir .venv/bin al PATH
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Descargar Artifact de fase 3 variants
        uses: actions/download-artifact@v4
        with:
          name: variant-f3v111-variants
          path: executions/03_preparewindowsds/variants.yaml

      - name: Descargar Artifact de fase 3
        uses: actions/download-artifact@v4
        with:
          name: run-f3v111-results
          path: executions/03_preparewindowsds/v111/
      
      - name: Crear variante Fase 4
        run: |
          make variant4 VARIANT=v201 PARENT=v111 PREDICTION_NAME=name OBJECTIVE="{operator: OR, events: [GRID_OVERVOLTAGE, INVERTER_FAULT]}"
      
      - name: Subir resultados de la variante
        uses: actions/upload-artifact@v4
        with:
          name: variant-f4v201-variants
          path: executions/04_targetengineering/variants.yaml
          retention-days: 1
      
      - name: Ejecutar script de Fase 4
        run: make script4-run VARIANT=v201

      - name: Subir ejecución de Fase 4
        uses: actions/upload-artifact@v4
        with:
          name: run-f4v201-results
          path: executions/04_targetengineering/v201/
          retention-days: 1

      - name: Verificar resultados de Fase 4
        run: make script4-check-results VARIANT=v201
      
# make variant4 VARIANT=v201 PARENT=v111  PREDICTION_NAME=name OBJECTIVE="{operator: OR, events: [GRID_OVERVOLTAGE, INVERTER_FAULT]}"
# make script4-run VARIANT=v201
# make script4-check-results VARIANT=v201

  fase5:
    needs: fase4
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11 y caché de pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: '**/requirements2-mlops.txt'

      - name: Crear .venv e instalar dependencias (rápido)
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements2-mlops.txt

      - name: Añadir .venv/bin al PATH
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Descargar Artifact de fase 4 variants
        uses: actions/download-artifact@v4
        with:
          name: variant-f4v201-variants
          path: executions/04_targetengineering/variants.yaml

      - name: Descargar Artifact de fase 4
        uses: actions/download-artifact@v4
        with:
          name: run-f4v201-results
          path: executions/04_targetengineering/v201/
      
      - name: Crear variante Fase 5
        run: make variant5 VARIANT=v301 PARENT=v201 MODEL_FAMILY=dense_bow IMBALANCE_STRATEGY=rare_events IMBALANCE_MAX_MAJ=20000
      
      - name: Subir resultados de la variante
        uses: actions/upload-artifact@v4
        with:
          name: variant-f5v301-variants
          path: executions/05_modeling/variants.yaml
          retention-days: 1
      
      - name: Ejecutar script de Fase 5
        run: make script5-run VARIANT=v301

      - name: Subir ejecución de Fase 5
        uses: actions/upload-artifact@v4
        with:
          name: run-f5v301-results
          path: executions/05_modeling/v301/
          retention-days: 1

      - name: Verificar resultados de Fase 5
        run: make script5-check-results VARIANT=v301

# make variant5 VARIANT=v111 PARENT=v101 MODEL_FAMILY=dense_bow IMBALANCE_STRATEGY=rare_events IMBALANCE_MAX_MAJ=20000
# make script5-run VARIANT=v301
# make script5-check-results VARIANT=v301