name: Check If we can download data from DVC

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-cache:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    env:
      GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
      GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
      TOKEN_GDRIVE_JSON: ${{ secrets.TOKEN_GDRIVE_JSON }}
      FASE0_FOLDER_ID: ${{ vars.FASE0_FOLDER_ID }}
      FASE1_FOLDER_ID: ${{ vars.FASE1_FOLDER_ID }}
      FASE2_FOLDER_ID: ${{ vars.FASE2_FOLDER_ID }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Restaurar o guardar caché del .venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements2-mlops.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Crear .venv e instalar dependencias
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements2-mlops.txt

      - name: Añadir .venv/bin al PATH
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Validar secrets requeridos
        run: |
          test -n "$GDRIVE_CLIENT_ID" || (echo "Falta secret GDRIVE_CLIENT_ID" && exit 1)
          test -n "$GDRIVE_CLIENT_SECRET" || (echo "Falta secret GDRIVE_CLIENT_SECRET" && exit 1)
          test -n "$FASE0_FOLDER_ID" || (echo "Falta variable FASE0_FOLDER_ID" && exit 1)
          test -n "$TOKEN_GDRIVE_JSON" || (echo "Falta secret TOKEN_GDRIVE_JSON" && exit 1)
          # test -n "$TOKEN_GDRIVE_DVC_JSON" || (echo "Falta secret TOKEN_GDRIVE_DVC_JSON" && exit 1)

      - name: Crear token.json de GDrive
        run: |
          # Token de GDrive
          printf '%s' "$TOKEN_GDRIVE_JSON" > .mlops_tools/token.json
          test -s .mlops_tools/token.json || (echo "token.json vacio" && exit 1)
          printf '%s' "$TOKEN_GDRIVE_JSON" > token.json
          test -s token.json || (echo "token.json vacio" && exit 1)
          # Token de dvc
          # printf '%s' "$TOKEN_GDRIVE_DVC_JSON" > .mlops_tools/dvc_token.json
          # test -s .mlops_tools/dvc_token.json || (echo "dvc_token.json vacio" && exit 1)


      - name: Configurar DVC remote (GDrive)
        working-directory: .mlops_tools
        run: make dvc_setup_fase0

      - name: Descargar datos de DVC
        working-directory: .mlops_tools
        run: make dvc_pull_fase0 

      - name: Verificar que los datos se descargaron
        run: |
          ls -la data
          wc data/raw.csv