name: Pipeline MLOps - DVC y Fases

on:
  pull_request:
    branches: ["main"]

  # push:
    # branches: ["main"]
  # pull_request:
  #   branches: ["main"]
permissions:
  contents: write

jobs:
  fase1:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tehedor/mlops_actions/mlops-env:latest
    env:
      USE_VENV: 0
      DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # ESTO SOLUCIONA EL DETACHED HEAD PARA TU MAKEFILE
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Configurar Git para la automatización
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Configurar DVC
        run: |
          dvc remote modify storage --local auth basic
          dvc remote modify storage --local user Tehedor
          dvc remote modify storage --local password ${{ secrets.DAGSHUB_TOKEN }}

      - name: DVC Pull para obtener los datos
        run: dvc pull data/raw.csv.dvc

      - name: Verificar datos
        run: |
          ls -la data
          wc data/raw.csv

      - name: Ejecutar Fases (Fase 1, Script)
        run: |
          make variant1 VARIANT=v001 RAW=./data/raw.csv CLEANING_STRATEGY=basic NAN_VALUES="[-999999]"
          make script1-run VARIANT=v001
      - name: Verificar resultados de la fase 1
        run: make script1-check-results VARIANT=v001

      - name: Publicar Variante (El Makefile hace el Commit)
        run: |
          # Tu Makefile hará el git add y el git commit aquí.
          make publish1 VARIANT=v001

      - name: Empujar resultados directamente a MAIN
        run: |
          # Como el Makefile ya ha commiteado, solo tenemos que coger nuestro HEAD 
          # y empujarlo a la rama main del repositorio remoto.
          git push origin HEAD:main