name: "🃏♻️ Reusable: Fase setup"

on:
  workflow_call:
    inputs:
      variant_id:
        required: true
        type: string
      parent_variant:
        required: true
        type: string
      params_json:
        required: true
        type: string
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - '*'

jobs:
  ejecutar-fase-2:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tehedor/mlops_actions/mlops-env:latest
    env:
      VARIANT_ID: ${{ inputs.variant_id }}
      PARENT_VARIANT: ${{ inputs.parent_variant }}
      PARAMS_JSON: ${{ inputs.params_json }}
    steps:
      - name: 1. Clean setup
        run: make clean-setup

      - name: 2. Setup remoto
        run: make setup SETUP_CFG=setup/remote.yaml

      - name: 3. Check setup
        run: make check-setup