name: "🃏♻️ Reusable: Fase setup"

on:
  push:
    branches:
      - main
    paths:
      - "**"
  # workflow_call: 
    # inputs:
    #   variant_id:
    #     required: true
    #     type: string
    #   parent_variant:
    #     required: true
    #     type: string
    #   params_json:
    #     required: true
    #     type: string

jobs:
  ejecutar-fase-0:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tehedor/mlops_actions/mlops-env:latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    env:
      USE_VENV: 0
      DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      # VARIANT_ID: ${{ inputs.variant_id }}
      # PARENT_VARIANT: ${{ inputs.parent_variant }}
      # PARAMS_JSON: ${{ inputs.params_json }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Validar workspace
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          pwd
          ls -la
          test -f Makefile || (echo "[ERROR] No existe Makefile en el workspace"; exit 1)

      - name: 1. Clean setup
        run: make clean-setup

      - name: 2. Setup remoto
        run: make setup SETUP_CFG=setup/remote.yaml

      # - name: Configure DVC credentials
      #   run: |
      #     dvc remote modify origin --local auth basic
      #     dvc remote modify origin --local user Tehedor
      #     dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}

      - name: Mostrar comandos de setup disponibles
        run: |
          make -n help-setup > /tmp/help-setup.txt
          head -n 5 /tmp/help-setup.txt
          echo '---'

      - name: Mostrar la configuración de dvc.
        run: cat .dvc/config

      - name: Mostar los files de dvc
        run: ls -la .dvc

      - name: 3. Check setup
        run: make check-setup

      - name: Probar si descarga de DVC funciona
        run: dvc pull -R data/raw